use_frameworks!

platform :ios, '8.0'

target 'LPBLESetupiOS_Example' do
  pod 'LPBLESetupiOS', :path => '../'

  target 'LPBLESetupiOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
